export enum CART_ACTIONS {
  ADD_PRODUCT = '[CART] ADD_PRODUCT',
  REMOVE_PRODUCT = '[CART] REMOVE_PRODUCT',
  INCREMENT_PRODUCT = '[CART] INCREMENT_PRODUCT',
  DECREMENT_PRODUCT = '[CART] DECREMENT_PRODUCT',
}

export enum GAMES_ACTIONS {
  SET_GAMES = '[GAMES] SET_GAMES'
}
